/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/

#ifndef FILTERCONTROLLER_H
#define FILTERCONTROLLER_H

#include <qgsproject.h>
#include <qqmlintegration.h>
#include <QVariantList>

class QgsVectorLayer;
class QgsMapLayer;

/**
 * @brief Single field filter definition
 */
struct FieldFilter
{
    Q_GADGET
    QML_ELEMENT
    QML_UNCREATABLE( "Full FieldFilter is not exposed to QML, use only the exposed enum." )

  public:
    enum FilterType
    {
      TextFilter,
      NumberFilter,
      DateFilter,
      CheckboxFilter,
      SingleSelectFilter,
      MultiSelectFilter
    };
    Q_ENUM( FilterType )

    QString filterId;       // generated ID (not persistent) for faster lookup
    QString filterName;     // name of filter as set by user
    FilterType filterType;
    QString layerId;        // ID of layer this filter applies on
    QString fieldName;      // name of field, which gets filtered
    QString sqlExpression;  // SQL expression generated by plugin
    QVariant value;         // single value (text, checkbox) or list of values (date, number, single/multi select)
    QString provider;       // data provider type

    bool isValid() const
    {
      const bool hasValue = value.isValid() && !value.isNull();
      const bool isNamed = !filterName.isEmpty();
      return isNamed && hasValue && hasFilterInfo();
    }

    bool hasFilterInfo() const
    {
      return !layerId.isEmpty() && !fieldName.isEmpty() && !sqlExpression.isEmpty();
    }
};


/**
 * @brief FilterController manages feature filtering across all layers in the project.
 *
 * It stores filter definitions per layer and generates QGIS filter expressions.
 * The filtering affects both map rendering and feature lists.
 */
class FilterController : public QObject
{
    Q_OBJECT

    /**
     * Whether filtering has been enabled in QGIS plugin on active project
     */
    Q_PROPERTY( bool filteringAvailable READ hasFiltersAvailable NOTIFY hasFiltersAvailableChanged )

    /**
     * Whether filtering is currently active (can be temporarily disabled)
     */
    Q_PROPERTY( bool filteringEnabled READ hasFiltersEnabled WRITE setFiltersEnabled NOTIFY hasFiltersEnabledChanged )

  public:
    explicit FilterController( QObject *parent = nullptr );
    ~FilterController() override = default;

    /**
     * Gets list of all available filters
     * \return QVariantList of QVariantMaps, which has subset of properties from FieldFilter
     */
    Q_INVOKABLE QVariantList getFilters() const;

    /**
     * Receives the set values for filtering, saves them and applies them to layers
     */
    Q_INVOKABLE void processFilters( const QVariantMap &newFilters );

    /**
     * @brief Clears all filters for a specific layer
     */
    Q_INVOKABLE void clearLayerFilters( const QString &layerId );

    /**
     * @brief Clears all filters for all layers
     */
    Q_INVOKABLE void clearAllFilters();

    // Indicates if the filter with filterId should use unique values, value relation or value map + returns configs for each
    Q_INVOKABLE QVariantMap getDropdownConfiguration( const QString &filterId );

    /**
     * Queries whether there is any filtering active on the layer specified by ID. Essentially just checks the
     * subsetString of layer.
     */
    Q_INVOKABLE bool hasActiveFilterOnLayer( const QString &layerId );

    bool hasFiltersAvailable() const;

    bool hasFiltersEnabled() const;

    void setFiltersEnabled( bool filtersEnabled );


  signals:
    void filtersChanged();
    void hasActiveFiltersChanged();
    void layerFilterChanged( const QString &layerId );
    void hasFiltersAvailableChanged();
    void hasFiltersEnabledChanged();

  public slots:

    /**
     * Gets triggered when active project changes. Loads filtering config from project file and initializes everything.
     */
    void loadFilterConfig( const QgsProject *project );

  private:
    /**
     * @brief Applies filters to all vector layers in the current project
     */
    void applyFiltersToAllLayers();

    /**
     * @brief Applies the current filters to a vector layer's subset string
     * @param layer The layer to apply filters to
     */
    void applyFiltersToLayer( QgsVectorLayer *layer );

    /**
     * @brief Generates a QGIS filter expression string for a layer
     * @param layerId The layer ID
     * @return Filter expression string, empty if no filters active
     */
    QString generateFilterExpression( const QString &layerId ) const;

    /**
     * Sets filter values for expression and generates usable field filter expression
     * \return String of usable SQL expression
     */
    QString buildFieldExpression( const FieldFilter &filter ) const;

    QList<FieldFilter> mFieldFilters;

    bool mFilteringAvailable = false;
    bool mFilteringEnabled = false;
};

#endif // FILTERCONTROLLER_H
