/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/

#include "trimblepositionprovider.h"

#include <QDesktopServices>
#include <QJsonDocument>
#include <QJsonObject>
#include <QUrl>

#include <qgscoordinatereferencesystem.h>
#include <qgsgpsconnection.h>
#include <qgslogger.h>

#ifdef ANDROID
#include <QJniObject>
#include <QtCore/private/qandroidextras_p.h>
#endif

// trimblesecrets.cpp is generated by decrypting trimblesecrets.cpp.enc.
// It defines static QString __getTrimbleAppId().
#include "trimblesecrets.cpp"

constexpr int ONE_SECOND_MS = 1000;
constexpr int TMM_WS_V2_DEFAULT_PORT = 9639;

// ---------------------------------------------------------------------------
// Frame resolver
// ---------------------------------------------------------------------------

struct FrameEntry
{
  const char *name;    // prefix match against targetReferenceFrameName
  const char *authId;  // EPSG or user authority identifier
};

static const FrameEntry KNOWN_FRAMES[] =
{
  { "WGS 84",      "EPSG:4979" },
  { "WGS84",       "EPSG:4979" },
  { "ITRF2020",    "EPSG:9990" },
  { "ITRF2014",    "EPSG:7912" },
  { "ITRF2008",    "EPSG:8999" },
  { "ITRF2005",    "EPSG:8998" },
  { "ITRF2000",    "EPSG:8997" },
  { "ITRF97",      "EPSG:8996" },
  { "ITRF96",      "EPSG:8995" },
  { "ITRF94",      "EPSG:8994" },
  { "ITRF93",      "EPSG:8993" },
  { "ITRF92",      "EPSG:8992" },
  { "ITRF91",      "EPSG:8991" },
  { "ITRF90",      "EPSG:8990" },
  { "ITRF89",      "EPSG:8989" },
  { "ITRF88",      "EPSG:8988" },
  { "NAD83(2011)", "EPSG:6319" },
  { "NAD83",       "EPSG:4269" },
  { "ETRS89",      "EPSG:4936" },
  { "GDA2020",     "EPSG:7843" },
  { "GDA94",       "EPSG:4939" },
  { nullptr, nullptr }
};

QgsCoordinateReferenceSystem TrimblePositionProvider::resolveFrame( const QString &frameName, double epoch )
{
  if ( frameName.isEmpty() )
    return QgsCoordinateReferenceSystem( QStringLiteral( "EPSG:4979" ) ); // WGS84 default

  for ( const FrameEntry *e = KNOWN_FRAMES; e->name; ++e )
  {
    if ( frameName.startsWith( QLatin1String( e->name ), Qt::CaseInsensitive ) )
    {
      QgsCoordinateReferenceSystem crs( QString::fromLatin1( e->authId ) );
      if ( epoch > 0 )
        crs.setCoordinateEpoch( epoch );
      return crs;
    }
  }

  QgsDebugMsgLevel( QStringLiteral( "TrimblePositionProvider: unknown frame '%1', falling back to WGS84" ).arg( frameName ), 2 );
  return QgsCoordinateReferenceSystem( QStringLiteral( "EPSG:4979" ) );
}

// ---------------------------------------------------------------------------
// Message parser
// ---------------------------------------------------------------------------

GeoPosition TrimblePositionProvider::parseLocationMessage( const QString &json )
{
  GeoPosition pos;

  const QJsonDocument doc = QJsonDocument::fromJson( json.toUtf8() );
  if ( doc.isNull() || !doc.isObject() )
    return pos;

  const QJsonObject obj = doc.object();

  if ( obj.contains( QStringLiteral( "latitude" ) ) && !obj.value( QStringLiteral( "latitude" ) ).isNull() )
    pos.latitude = obj.value( QStringLiteral( "latitude" ) ).toDouble( std::numeric_limits<double>::quiet_NaN() );

  if ( obj.contains( QStringLiteral( "longitude" ) ) && !obj.value( QStringLiteral( "longitude" ) ).isNull() )
    pos.longitude = obj.value( QStringLiteral( "longitude" ) ).toDouble( std::numeric_limits<double>::quiet_NaN() );

  if ( obj.contains( QStringLiteral( "altitude" ) ) && !obj.value( QStringLiteral( "altitude" ) ).isNull() )
    pos.elevation = obj.value( QStringLiteral( "altitude" ) ).toDouble( std::numeric_limits<double>::quiet_NaN() );

  if ( obj.contains( QStringLiteral( "hdop" ) ) && !obj.value( QStringLiteral( "hdop" ) ).isNull() )
    pos.hdop = obj.value( QStringLiteral( "hdop" ) ).toDouble( -1 );

  if ( obj.contains( QStringLiteral( "totalSatInUse" ) ) && !obj.value( QStringLiteral( "totalSatInUse" ) ).isNull() )
    pos.satellitesUsed = obj.value( QStringLiteral( "totalSatInUse" ) ).toInt( -1 );

  if ( obj.contains( QStringLiteral( "satellites" ) ) && !obj.value( QStringLiteral( "satellites" ) ).isNull() )
    pos.satellitesVisible = obj.value( QStringLiteral( "satellites" ) ).toInt( -1 );

  // diffStatus: 1=Autonomous, 2=DGPS, 4=Fixed, 5=Float
  const int diffStatus = obj.value( QStringLiteral( "diffStatus" ) ).toInt( 1 );
  switch ( diffStatus )
  {
    case 4:
      pos.qualityIndicator = Qgis::GpsQualityIndicator::RTK;
      break;
    case 5:
      pos.qualityIndicator = Qgis::GpsQualityIndicator::FloatRTK;
      break;
    case 2:
      pos.qualityIndicator = Qgis::GpsQualityIndicator::DGPS;
      break;
    default:
      pos.qualityIndicator = Qgis::GpsQualityIndicator::GPS;
      break;
  }

  // TMM has already reduced its output to the ground point.
  // antennaHeight here is the value TMM applied (metadata only); the app must NOT subtract it again.
  if ( obj.contains( QStringLiteral( "antennaHeight" ) ) && !obj.value( QStringLiteral( "antennaHeight" ) ).isNull() )
  {
    pos.antennaHeight = obj.value( QStringLiteral( "antennaHeight" ) ).toDouble( -1 );
    pos.antennaHeightApplied = true;
  }

  return pos;
}

// ---------------------------------------------------------------------------
// Constructor / destructor
// ---------------------------------------------------------------------------

TrimblePositionProvider::TrimblePositionProvider( const QString &id, const QString &name, PositionTransformer &positionTransformer, QObject *parent )
  : AbstractPositionProvider( id, QStringLiteral( "external_trimble" ), name, positionTransformer, parent )
  , mSecondsLeftToReconnect( ReconnectDelay::ShortDelay / ONE_SECOND_MS )
{
  mRegistration = new TrimbleRegistration( this );
  connect( mRegistration, &TrimbleRegistration::registered, this, &TrimblePositionProvider::onRegistered );
  connect( mRegistration, &TrimbleRegistration::failed, this, &TrimblePositionProvider::onRegistrationFailed );

  mReconnectTimer.setSingleShot( false );
  mReconnectTimer.setInterval( ONE_SECOND_MS );
  connect( &mReconnectTimer, &QTimer::timeout, this, &TrimblePositionProvider::onReconnectTimeout );

  mHeartBeatTimer.setSingleShot( true );
  connect( &mHeartBeatTimer, &QTimer::timeout, this, [this]
  {
    setState( tr( "No data from Trimble Mobile Manager" ), State::NoConnection );
    emit positionChanged( GeoPosition() );
    startReconnectTimer();
  } );

  TrimblePositionProvider::startUpdates();
}

TrimblePositionProvider::~TrimblePositionProvider()
{
  TrimblePositionProvider::closeProvider();
}

void TrimblePositionProvider::startUpdates()
{
  if ( mRegistrationInProgress )
  {
    qDebug() << "TrimblePositionProvider: startUpdates called while registration already in progress, ignoring";
    return;
  }
  if ( mCachedPort > 0 )
  {
    qDebug() << "TrimblePositionProvider: startUpdates - reconnecting with cached port" << mCachedPort;
    connectWebSocket( mCachedPort );
    return;
  }
  mRegistrationInProgress = true;
  qDebug() << "TrimblePositionProvider: startUpdates - requesting registration";
  setState( tr( "Connecting to Trimble Mobile Manager" ), State::Connecting );
  mRegistration->requestRegistration( __getTrimbleAppId() );
}

void TrimblePositionProvider::stopUpdates()
{
  mHeartBeatTimer.stop();
  mReconnectTimer.stop();
  if ( mSocket && mSocket->state() == QAbstractSocket::ConnectedState )
    mSocket->close();
}

void TrimblePositionProvider::closeProvider()
{
  mHeartBeatTimer.stop();
  mReconnectTimer.stop();
  if ( mSocket )
  {
    mSocket->disconnect();
    mSocket->abort();
  }
}

QgsCoordinateReferenceSystem TrimblePositionProvider::sourceCrs() const
{
  return mSourceCrs;
}

// ---------------------------------------------------------------------------
// Private slots
// ---------------------------------------------------------------------------

void TrimblePositionProvider::onRegistered( int port )
{
  qDebug() << "TrimblePositionProvider: registration succeeded, port:" << port;
  mRegistrationInProgress = false;
  mCachedPort = port;
  connectWebSocket( port );
}

void TrimblePositionProvider::onRegistrationFailed( const QString &reason )
{
  qDebug() << "TrimblePositionProvider: registration failed:" << reason;
  mRegistrationInProgress = false;
  setState( reason, State::NoConnection );
  emit positionChanged( GeoPosition() );
}

void TrimblePositionProvider::connectWebSocket( int port )
{
  mSocket = std::make_unique<QWebSocket>();

  connect( mSocket.get(), &QWebSocket::textMessageReceived, this, &TrimblePositionProvider::onTextMessageReceived );
  connect( mSocket.get(), &QWebSocket::disconnected, this, &TrimblePositionProvider::onSocketDisconnected );
  connect( mSocket.get(), QOverload<QAbstractSocket::SocketError>::of( &QWebSocket::error ),
           this, &TrimblePositionProvider::onSocketError );
  connect( mSocket.get(), &QWebSocket::connected, this, [this]
  {
    setState( tr( "Connected to Trimble Mobile Manager" ), State::Connected );
    mReconnectDelay = ReconnectDelay::ShortDelay;
    mHeartBeatTimer.start( ReconnectDelay::ExtraLongDelay );
  } );

  const QUrl url( QStringLiteral( "ws://127.0.0.1:%1/" ).arg( port ) );
  setState( tr( "Connecting to Trimble Mobile Manager" ), State::Connecting );
  mSocket->open( url );
}

void TrimblePositionProvider::onTextMessageReceived( const QString &message )
{
  mHeartBeatTimer.start( ReconnectDelay::ExtraLongDelay );

  // Parse once; keep antenna-height fields through the position transformer
  GeoPosition raw = parseLocationMessage( message );
  const double antennaHeight = raw.antennaHeight;
  const bool antennaHeightApplied = raw.antennaHeightApplied;

  GeoPosition pos = mPositionTransformer->processNetworkPosition( raw );
  pos.antennaHeight = antennaHeight;
  pos.antennaHeightApplied = antennaHeightApplied;

  setState( tr( "Connected to Trimble Mobile Manager" ), State::Connected );
  emit positionChanged( pos );

  // Update source CRS from reported frame (re-resolve only on change)
  const QJsonDocument doc = QJsonDocument::fromJson( message.toUtf8() );
  if ( !doc.isNull() && doc.isObject() )
  {
    const QJsonObject obj = doc.object();
    const QString frameName = obj.value( QStringLiteral( "targetReferenceFrameName" ) ).toString();
    const double epoch = obj.value( QStringLiteral( "targetReferenceFrameEpoch" ) ).toDouble( 0 );
    const QgsCoordinateReferenceSystem newCrs = resolveFrame( frameName, epoch );

    if ( newCrs != mSourceCrs )
    {
      mSourceCrs = newCrs;
      emit sourceCrsChanged( mSourceCrs );
    }
  }
}

void TrimblePositionProvider::onSocketError( QAbstractSocket::SocketError error )
{
  Q_UNUSED( error )
  setState( tr( "Connection error: %1" ).arg( mSocket ? mSocket->errorString() : QString() ), State::NoConnection );
  emit positionChanged( GeoPosition() );
  startReconnectTimer();
}

void TrimblePositionProvider::onSocketDisconnected()
{
  mHeartBeatTimer.stop();
  setState( tr( "Disconnected from Trimble Mobile Manager" ), State::NoConnection );
  emit positionChanged( GeoPosition() );
  startReconnectTimer();
}

void TrimblePositionProvider::startReconnectTimer()
{
  mSecondsLeftToReconnect = mReconnectDelay / ONE_SECOND_MS;
  setState( tr( "Reconnecting in %1 s" ).arg( mSecondsLeftToReconnect ), State::WaitingToReconnect );
  mReconnectTimer.start();

  if ( mReconnectDelay == ReconnectDelay::ShortDelay )
    mReconnectDelay = ReconnectDelay::LongDelay;
}

void TrimblePositionProvider::onReconnectTimeout()
{
  if ( mSecondsLeftToReconnect <= 1 )
  {
    reconnect();
  }
  else
  {
    mSecondsLeftToReconnect--;
    setState( tr( "Reconnecting in %1 s" ).arg( mSecondsLeftToReconnect ), State::WaitingToReconnect );
  }
}

void TrimblePositionProvider::reconnect()
{
  mReconnectTimer.stop();
  if ( mCachedPort > 0 )
  {
    connectWebSocket( mCachedPort );
  }
  else
  {
    startUpdates(); // re-register
  }
}

void TrimblePositionProvider::openAntennaHeightPage()
{
#ifdef ANDROID
  QJniObject intentAction = QJniObject::fromString( QStringLiteral( "com.trimble.tmm.OPENANTENNAHEIGHT" ) );
  QJniObject intent( "android/content/Intent", "(Ljava/lang/String;)V", intentAction.object<jstring>() );
  QJniObject activity = QJniObject::callStaticObjectMethod( "org/qtproject/qt/android/QtNative",
                        "activity",
                        "()Landroid/app/Activity;" );
  if ( activity.isValid() )
    activity.callMethod<void>( "startActivity", "(Landroid/content/Intent;)V", intent.object() );
#elif defined(Q_OS_IOS)
  QDesktopServices::openUrl( QUrl( QStringLiteral( "TmmOpenToAntennaHeight://trimble.tmm.iOS" ) ) );
#endif
}
