/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/

#include "trimblepositionprovider.h"

#include <QDesktopServices>
#include <QJsonDocument>
#include <QJsonObject>
#include <QUrl>

#include <qgscoordinatereferencesystem.h>
#include <qgsgpsconnection.h>
#include <qgslogger.h>

#ifdef ANDROID
#include <QJniObject>
#include <QtCore/private/qandroidextras_p.h>
#endif

#include "coreutils.h"
// trimblesecrets.cpp is generated by decrypting trimblesecrets.cpp.enc.
// It defines static QString __getTrimbleAppId().
#include "trimblesecrets.cpp"

constexpr int ONE_SECOND_MS = 1000;
constexpr int TMM_WS_V2_DEFAULT_PORT = 9639;
// Trimble reports just 2D CRS however we have here the 3D variant for further elevation processing
const QHash<QString, QString> TRIMBLE_REFERENCE_FRAMES =
{
  { QStringLiteral( "BGS2005" ), QStringLiteral( "EPSG:7797" ) },
  { QStringLiteral( "CGCS2000" ), QStringLiteral( "EPSG:4480" ) },
  { QStringLiteral( "CR-SIRGAS" ), QStringLiteral( "EPSG:8906" ) },
  { QStringLiteral( "EST97" ), QStringLiteral( "EPSG:4935" ) },
  { QStringLiteral( "ETRF1989" ), QStringLiteral( "EPSG:7914" ) },
  { QStringLiteral( "ETRF2000" ), QStringLiteral( "EPSG:4937" ) },
  { QStringLiteral( "ETRF2000 (EPOCH:2010.5)" ), QStringLiteral( "EPSG:4937" ) },
  { QStringLiteral( "ETRS89-D96-17" ), QStringLiteral( "EPSG:4937" ) },
  { QStringLiteral( "ETRS89-DREF91(R16)" ), QStringLiteral( "EPSG:4937" ) },
  { QStringLiteral( "EUREF-DK15" ), QStringLiteral( "EPSG:4937" ) },
  { QStringLiteral( "EUREF-DK94" ), QStringLiteral( "EPSG:4937" ) },
  { QStringLiteral( "EUREF-FIN" ), QStringLiteral( "EPSG:4937" ) },
  { QStringLiteral( "EUREF-NKG-2003" ), QStringLiteral( "EPSG:4951" ) },
  { QStringLiteral( "EUREF89" ), QStringLiteral( "EPSG:4937" ) },
  { QStringLiteral( "GDA2020" ), QStringLiteral( "EPSG:7843" ) },
  { QStringLiteral( "GDA94" ), QStringLiteral( "EPSG:4939" ) },
  { QStringLiteral( "ISN2016" ), QStringLiteral( "EPSG:8085" ) },
  { QStringLiteral( "ITRF1993" ), QStringLiteral( "EPSG:7905" ) },
  { QStringLiteral( "ITRF2000" ), QStringLiteral( "EPSG:7909" ) },
  { QStringLiteral( "ITRF2005" ), QStringLiteral( "EPSG:7910" ) },
  { QStringLiteral( "ITRF2008" ), QStringLiteral( "EPSG:7911" ) },
  { QStringLiteral( "ITRF2008-India-CORS" ), QStringLiteral( "EPSG:8999" ) },
  { QStringLiteral( "ITRF2008-Mexico" ), QStringLiteral( "EPSG:6364" ) },
  { QStringLiteral( "ITRF2014" ), QStringLiteral( "EPSG:7912" ) },
  { QStringLiteral( "ITRF2020" ), QStringLiteral( "EPSG:9989" ) },
  { QStringLiteral( "JGD2000" ), QStringLiteral( "EPSG:4947" ) },
  { QStringLiteral( "JGD2011" ), QStringLiteral( "EPSG:6667" ) },
  { QStringLiteral( "KGD2002" ), QStringLiteral( "EPSG:4927" ) },
  { QStringLiteral( "KSA-GRF17" ), QStringLiteral( "EPSG:9332" ) },
  { QStringLiteral( "LKS-92" ), QStringLiteral( "EPSG:4949" ) },
  { QStringLiteral( "MAGNA-SIRGAS" ), QStringLiteral( "EPSG:4997" ) },
  { QStringLiteral( "MAGNA-SIRGAS(2018)" ), QStringLiteral( "EPSG:4997" ) },
  { QStringLiteral( "MTRF-2000" ), QStringLiteral( "EPSG:8817" ) },
  { QStringLiteral( "NAD83(2011) (EPOCH:2010)" ), QStringLiteral( "EPSG:6319" ) },
  { QStringLiteral( "NAD83(2011) (EPOCH:2017.5)" ), QStringLiteral( "EPSG:6319" ) },
  { QStringLiteral( "NAD83(CORS96) (EPOCH:2002)" ), QStringLiteral( "EPSG:6782" ) },
  { QStringLiteral( "NAD83(CSRS)v7 (EPOCH:1997)" ), QStringLiteral( "EPSG:8254" ) },
  { QStringLiteral( "NAD83(CSRS)v7 (EPOCH:2002)" ), QStringLiteral( "EPSG:8254" ) },
  { QStringLiteral( "NAD83(CSRS)v7 (EPOCH:2010)" ), QStringLiteral( "EPSG:8254" ) },
  { QStringLiteral( "NAD83(CSRS)v8 (EPOCH:1997)" ), QStringLiteral( "EPSG:10413" ) },
  { QStringLiteral( "NAD83(CSRS)v8 (EPOCH:2002)" ), QStringLiteral( "EPSG:10413" ) },
  { QStringLiteral( "NAD83(CSRS)v8 (EPOCH:2010)" ), QStringLiteral( "EPSG:10413" ) },
  { QStringLiteral( "NAD83(MA11) (EPOCH:2010)" ), QStringLiteral( "EPSG:6324" ) },
  { QStringLiteral( "NAD83(PA11) (EPOCH:2010)" ), QStringLiteral( "EPSG:6321" ) },
  { QStringLiteral( "NZGD2000" ), QStringLiteral( "EPSG:4959" ) },
  { QStringLiteral( "OSNetv2009" ), QStringLiteral( "EPSG:4277" ) },  // TODO: create 3D CRS here
  { QStringLiteral( "POSGAR07" ), QStringLiteral( "EPSG:5342" ) },
  { QStringLiteral( "PZ-90.11" ), QStringLiteral( "EPSG:7680" ) },
  { QStringLiteral( "RDN2008" ), QStringLiteral( "EPSG:6705" ) },
  { QStringLiteral( "RGAF09" ), QStringLiteral( "EPSG:5488" ) },
  { QStringLiteral( "RGF93v2b" ), QStringLiteral( "EPSG:9781" ) },
  { QStringLiteral( "RGFG95" ), QStringLiteral( "EPSG:4967" ) },
  { QStringLiteral( "RGNC91-93" ), QStringLiteral( "EPSG:4907" ) },
  { QStringLiteral( "RGR92" ), QStringLiteral( "EPSG:4971" ) },
  { QStringLiteral( "RGTAAF07" ), QStringLiteral( "EPSG:7072" ) },
  { QStringLiteral( "SIRGAS-Chile 2016" ), QStringLiteral( "EPSG:9152" ) },
  { QStringLiteral( "SIRGAS-Chile 2021" ), QStringLiteral( "EPSG:20040" ) },
  { QStringLiteral( "SIRGAS-CON" ), QStringLiteral( "EPSG:4989" ) },
  { QStringLiteral( "SIRGAS-CON SIR17P01" ), QStringLiteral( "EPSG:8946" ) },
  { QStringLiteral( "SIRGAS-ROU98" ), QStringLiteral( "EPSG:5380" ) },
  { QStringLiteral( "SIRGAS2000" ), QStringLiteral( "EPSG:4989" ) },
  { QStringLiteral( "SWEREF99" ), QStringLiteral( "EPSG:4977" ) },
  { QStringLiteral( "WGS84 (current)" ), QStringLiteral( "EPSG:4979" ) },
};

TrimblePositionProvider::TrimblePositionProvider( const QString &id, const QString &name, PositionTransformer &positionTransformer, QObject *parent )
  : AbstractPositionProvider( id, QStringLiteral( "external_trimble" ), name, positionTransformer, parent )
  , mSecondsLeftToReconnect( ReconnectDelay::ShortDelay / ONE_SECOND_MS )
{
  mRegistration = new TrimbleRegistration( this );
  connect( mRegistration, &TrimbleRegistration::registered, this, &TrimblePositionProvider::onRegistered );
  connect( mRegistration, &TrimbleRegistration::failed, this, &TrimblePositionProvider::onRegistrationFailed );

  mReconnectTimer.setSingleShot( false );
  mReconnectTimer.setInterval( ONE_SECOND_MS );
  connect( &mReconnectTimer, &QTimer::timeout, this, &TrimblePositionProvider::onReconnectTimeout );

  mHeartBeatTimer.setSingleShot( true );
  connect( &mHeartBeatTimer, &QTimer::timeout, this, [this]
  {
    setState( tr( "No data" ), State::NoConnection );
    emit positionChanged( GeoPosition() );
    startReconnectTimer();
  } );

  TrimblePositionProvider::startUpdates();
}

TrimblePositionProvider::~TrimblePositionProvider()
{
  TrimblePositionProvider::closeProvider();
}

void TrimblePositionProvider::startUpdates()
{
  if ( mRegistrationInProgress )
  {
    return;
  }

  if ( mCachedPort > 0 )
  {
    connectWebSocket( mCachedPort );
    return;
  }

  mRegistrationInProgress = true;
  setState( tr( "Connecting" ), State::Connecting );
  mRegistration->requestRegistration( __getTrimbleAppId() );
}


void TrimblePositionProvider::stopUpdates()
{
  mHeartBeatTimer.stop();
  mReconnectTimer.stop();
  if ( mSocket && mSocket->state() == QAbstractSocket::ConnectedState )
    mSocket->close();
}

void TrimblePositionProvider::closeProvider()
{
  mHeartBeatTimer.stop();
  mReconnectTimer.stop();
  if ( mSocket )
  {
    mSocket->disconnect();
    mSocket->abort();
  }
}

QgsCoordinateReferenceSystem TrimblePositionProvider::resolveFrame( const QString &frameName, const double epoch )
{
  // fallback to PositionKit::positionCrsXXX()
  if ( frameName.isEmpty() ) return {};

  const QString crsId = TRIMBLE_REFERENCE_FRAMES.value( frameName );
  if ( !crsId.isEmpty() )
  {
    QgsCoordinateReferenceSystem newCrs( crsId );
    if ( epoch >= 0 )
    {
      newCrs.setCoordinateEpoch( epoch );
    }
    return newCrs;
  }

  CoreUtils::log( QStringLiteral( "TrimblePositionProvider" ), QStringLiteral( "TrimblePositionProvider: unknown frame '%1', falling back to WGS84" ).arg( frameName ) );
  return {};
}

GeoPosition TrimblePositionProvider::parseLocationMessage( const QString &json )
{
  GeoPosition pos;

  const QJsonDocument doc = QJsonDocument::fromJson( json.toUtf8() );
  if ( doc.isNull() || !doc.isObject() )
    return pos;

  const QJsonObject obj = doc.object();

  if ( obj.contains( QStringLiteral( "latitude" ) ) && !obj.value( QStringLiteral( "latitude" ) ).isNull() )
    pos.latitude = obj.value( QStringLiteral( "latitude" ) ).toDouble( std::numeric_limits<double>::quiet_NaN() );

  if ( obj.contains( QStringLiteral( "longitude" ) ) && !obj.value( QStringLiteral( "longitude" ) ).isNull() )
    pos.longitude = obj.value( QStringLiteral( "longitude" ) ).toDouble( std::numeric_limits<double>::quiet_NaN() );

  if ( obj.contains( QStringLiteral( "undulation" ) ) && !obj.value( QStringLiteral( "undulation" ) ).isNull() )
  {
    pos.elevation_diff = obj.value( QStringLiteral( "undulation" ) ).toDouble( std::numeric_limits<double>::quiet_NaN() );
    // prefer msl height if available
    if ( obj.contains( QStringLiteral( "mslHeight" ) ) && !obj.value( QStringLiteral( "mslHeight" ) ).isNull() )
    {
      pos.elevation = obj.value( QStringLiteral( "mslHeight" ) ).toDouble( std::numeric_limits<double>::quiet_NaN() );
    }
  }
  else if ( obj.contains( QStringLiteral( "altitude" ) ) && !obj.value( QStringLiteral( "altitude" ) ).isNull() )
  {
    pos.elevation = obj.value( QStringLiteral( "altitude" ) ).toDouble( std::numeric_limits<double>::quiet_NaN() );
  }

  if ( obj.contains( QStringLiteral( "speed" ) ) && !obj.value( QStringLiteral( "speed" ) ).isNull() )
  {
    pos.speed = obj.value( QStringLiteral( "speed" ) ).toDouble( -1 );
    // trimble reports speed in m/s, and speed in QgsGpsInformation is in km/h
    if ( pos.speed >= 0 ) pos.speed = pos.speed * 3.6;
  }

  if ( obj.contains( QStringLiteral( "bearing" ) ) && !obj.value( QStringLiteral( "bearing" ) ).isNull() )
    pos.direction = obj.value( QStringLiteral( "bearing" ) ).toDouble( -1 );

  if ( obj.contains( QStringLiteral( "pdop" ) ) && !obj.value( QStringLiteral( "pdop" ) ).isNull() )
    pos.pdop = obj.value( QStringLiteral( "pdop" ) ).toDouble( -1 );

  if ( obj.contains( QStringLiteral( "hdop" ) ) && !obj.value( QStringLiteral( "hdop" ) ).isNull() )
    pos.hdop = obj.value( QStringLiteral( "hdop" ) ).toDouble( -1 );

  if ( obj.contains( QStringLiteral( "vdop" ) ) && !obj.value( QStringLiteral( "vdop" ) ).isNull() )
    pos.vdop = obj.value( QStringLiteral( "vdop" ) ).toDouble( -1 );

  if ( obj.contains( QStringLiteral( "hrms" ) ) && !obj.value( QStringLiteral( "hrms" ) ).isNull() )
    pos.hacc = obj.value( QStringLiteral( "hrms" ) ).toDouble( -1 );

  if ( obj.contains( QStringLiteral( "vrms" ) ) && !obj.value( QStringLiteral( "vrms" ) ).isNull() )
    pos.vacc = obj.value( QStringLiteral( "vrms" ) ).toDouble( -1 );

  if ( obj.contains( QStringLiteral( "totalSatInUse" ) ) && !obj.value( QStringLiteral( "totalSatInUse" ) ).isNull() )
    pos.satellitesUsed = obj.value( QStringLiteral( "totalSatInUse" ) ).toInt( -1 );

  if ( obj.contains( QStringLiteral( "satellites" ) ) && !obj.value( QStringLiteral( "satellites" ) ).isNull() )
    pos.satellitesVisible = obj.value( QStringLiteral( "satellites" ) ).toInt( -1 );

  if ( obj.contains( QStringLiteral( "utcTimeStamp" ) ) && !obj.value( QStringLiteral( "utcTimeStamp" ) ).isNull() )
    pos.utcDateTime = obj.value( QStringLiteral( "utcTimeStamp" ) ).toVariant().toDateTime();

  const int diffStatus = obj.value( QStringLiteral( "diffStatus" ) ).toInt( -1 );
  switch ( diffStatus )
  {
    case 1:
      pos.qualityIndicator = Qgis::GpsQualityIndicator::GPS;
      break;
    case 2:
      pos.qualityIndicator = Qgis::GpsQualityIndicator::DGPS;
      break;
    case 4:
      pos.qualityIndicator = Qgis::GpsQualityIndicator::RTK;
      break;
    case 5:
      pos.qualityIndicator = Qgis::GpsQualityIndicator::FloatRTK;
      break;
    default:
      pos.qualityIndicator = Qgis::GpsQualityIndicator::Unknown;
      break;
  }
  pos.fixStatusString = pos.parseFixStatus();

  if ( obj.contains( QStringLiteral( "antennaHeight" ) ) && !obj.value( QStringLiteral( "antennaHeight" ) ).isNull() )
  {
    mAntennaHeight = obj.value( QStringLiteral( "antennaHeight" ) ).toDouble( std::numeric_limits<double>::quiet_NaN() );
  }

  const bool referenceFrameFieldExists = obj.contains( QStringLiteral( "targetReferenceFrameName" ) ) && !obj.value( QStringLiteral( "targetReferenceFrameName" ) ).isNull() ;
  const bool referenceFrameEpochFieldExists = obj.contains( QStringLiteral( "targetReferenceFrameEpoch" ) ) && !obj.value( QStringLiteral( "targetReferenceFrameEpoch" ) ).isNull();

  if ( referenceFrameFieldExists && referenceFrameEpochFieldExists )
  {
    const QString frameName = obj.value( QStringLiteral( "targetReferenceFrameName" ) ).toString();
    const double epoch = obj.value( QStringLiteral( "targetReferenceFrameEpoch" ) ).toDouble( -1 );
    const QgsCoordinateReferenceSystem newCrs = resolveFrame( frameName, epoch );

    if ( newCrs != mSourceCrs )
    {
      mSourceCrs = newCrs;
      mPositionTransformer->setSourceCrs( newCrs );
    }
  }

  if ( obj.contains( QStringLiteral( "geoidModel" ) ) && !obj.value( QStringLiteral( "geoidModel" ) ).isNull() )
  {
    mGeoidModelName = obj.value( QStringLiteral( "geoidModel" ) ).toString();
  }
  else
  {
    mGeoidModelName = QString();
  }

  return pos;
}

QgsCoordinateReferenceSystem TrimblePositionProvider::sourceCrs() const
{
  return mSourceCrs;
}

QString TrimblePositionProvider::geoidModelName() const
{
  return mGeoidModelName;
}

double TrimblePositionProvider::antennaHeight() const
{
  return mAntennaHeight;
}

void TrimblePositionProvider::onRegistered( const int port )
{
  mRegistrationInProgress = false;
  mCachedPort = port;
  connectWebSocket( port );
}

void TrimblePositionProvider::onRegistrationFailed( const QString &reason )
{
  mRegistrationInProgress = false;
  setState( reason, State::NoConnection );
  emit positionChanged( GeoPosition() );
}

void TrimblePositionProvider::connectWebSocket( const int port )
{
  mSocket = std::make_unique<QWebSocket>();

  connect( mSocket.get(), &QWebSocket::textMessageReceived, this, &TrimblePositionProvider::onTextMessageReceived );
  connect( mSocket.get(), &QWebSocket::disconnected, this, &TrimblePositionProvider::onSocketDisconnected );
  connect( mSocket.get(), &QWebSocket::errorOccurred, this, &TrimblePositionProvider::onSocketError );
  connect( mSocket.get(), &QWebSocket::connected, this, [this]
  {
    setState( tr( "Connected" ), State::Connected );
    mReconnectDelay = ReconnectDelay::ShortDelay;
    mHeartBeatTimer.start( ReconnectDelay::ExtraLongDelay );
  } );

  const QUrl url( QStringLiteral( "ws://localhost:%2" ).arg( port ) );
  setState( tr( "Connecting" ), State::Connecting );
  mSocket->open( url );
}

void TrimblePositionProvider::onTextMessageReceived( const QString &message )
{
  mHeartBeatTimer.start( ReconnectDelay::ExtraLongDelay );

  GeoPosition parsedPosition = parseLocationMessage( message );
  GeoPosition newPosition = mPositionTransformer->processTrimblePosition( parsedPosition );

  setState( tr( "Connected" ), State::Connected );
  emit positionChanged( newPosition );
}

void TrimblePositionProvider::onSocketError( const QAbstractSocket::SocketError error )
{
  Q_UNUSED( error )
  setState( tr( "Disconnected" ), State::NoConnection );
  CoreUtils::log( QStringLiteral( "TrimblePositionProvider" ), QStringLiteral( "Socket error occurred: %1" ).arg( mSocket->errorString() ) );
  emit positionChanged( GeoPosition() );
  startReconnectTimer();
}

void TrimblePositionProvider::onSocketDisconnected()
{
  mHeartBeatTimer.stop();
  setState( tr( "Disconnected" ), State::NoConnection );
  emit positionChanged( GeoPosition() );
  startReconnectTimer();
}

void TrimblePositionProvider::startReconnectTimer()
{
  mSecondsLeftToReconnect = mReconnectDelay / ONE_SECOND_MS;
  setState( tr( "Reconnecting in %1 s" ).arg( mSecondsLeftToReconnect ), State::WaitingToReconnect );
  mReconnectTimer.start();

  if ( mReconnectDelay == ReconnectDelay::ShortDelay )
    mReconnectDelay = ReconnectDelay::LongDelay;
}

void TrimblePositionProvider::onReconnectTimeout()
{
  if ( mSecondsLeftToReconnect <= 1 )
  {
    reconnect();
  }
  else
  {
    mSecondsLeftToReconnect--;
    setState( tr( "Reconnecting in %1 s" ).arg( mSecondsLeftToReconnect ), State::WaitingToReconnect );
  }
}

void TrimblePositionProvider::reconnect()
{
  mReconnectTimer.stop();
  if ( mCachedPort > 0 )
  {
    connectWebSocket( mCachedPort );
  }
  else
  {
    startUpdates(); // re-register
  }
}

void TrimblePositionProvider::openAntennaHeightPage()
{
#ifdef ANDROID
  QJniObject intentAction = QJniObject::fromString( QStringLiteral( "com.trimble.tmm.OPENANTENNAHEIGHT" ) );
  QJniObject intent( "android/content/Intent", "(Ljava/lang/String;)V", intentAction.object<jstring>() );
  QJniObject activity = QJniObject::callStaticObjectMethod( "org/qtproject/qt/android/QtNative",
                        "activity",
                        "()Landroid/app/Activity;" );
  if ( activity.isValid() )
    activity.callMethod<void>( "startActivity", "(Landroid/content/Intent;)V", intent.object() );
#elif defined(Q_OS_IOS)
  QDesktopServices::openUrl( QUrl( QStringLiteral( "TmmOpenToAntennaHeight://trimble.tmm.iOS" ) ) );
#endif
}
