#############################################################################
# Makefile for building: Input.app/Contents/MacOS/Input
# Generated by qmake (3.1) (Qt 5.14.2)
# Project:  ../app/input.pro
# Template: app
# Command: /opt/Qt/5.14.2/ios/bin/qmake -o Input.xcodeproj/project.pbxproj ../app/input.pro -spec macx-xcode CONFIG+=release CONFIG+=iphoneos CONFIG+=device CONFIG+=qtquickcompiler QMAKE_MAC_XCODE_SETTINGS+=qprofile qprofile.name=PROVISIONING_PROFILE_SPECIFIER qprofile.value=LutraConsultingLtd.Input.AppStore QMAKE_MAC_XCODE_SETTINGS+=qteam qteam.name=DEVELOPMENT_TEAM qteam.value=79QMH2QRAH QMAKE_MAC_XCODE_SETTINGS+=qidentity qidentity.name=CODE_SIGN_IDENTITY 'qidentity.value=iPhone Distribution: LUTRA CONSULTING LIMITED (79QMH2QRAH)' QMAKE_MAC_XCODE_SETTINGS+=qstyle qstyle.name=CODE_SIGN_STYLE qstyle.value=Manual
#############################################################################

MAKEFILE      = project.pbxproj

EQ            = =

QMAKE    = /opt/Qt/5.14.2/ios/bin/qmake
Input.xcodeproj/project.pbxproj: ../app/input.pro /opt/Qt/5.14.2/ios/mkspecs/macx-ios-clang/qmake.conf /opt/Qt/5.14.2/ios/mkspecs/features/spec_pre.prf \
		/opt/Qt/5.14.2/ios/mkspecs/qdevice.pri \
		/opt/Qt/5.14.2/ios/mkspecs/features/device_config.prf \
		/opt/Qt/5.14.2/ios/mkspecs/common/unix.conf \
		/opt/Qt/5.14.2/ios/mkspecs/common/mac.conf \
		/opt/Qt/5.14.2/ios/mkspecs/common/uikit.conf \
		/opt/Qt/5.14.2/ios/mkspecs/common/ios.conf \
		/opt/Qt/5.14.2/ios/mkspecs/common/sanitize.conf \
		/opt/Qt/5.14.2/ios/mkspecs/common/gcc-base.conf \
		/opt/Qt/5.14.2/ios/mkspecs/common/gcc-base-mac.conf \
		/opt/Qt/5.14.2/ios/mkspecs/common/clang.conf \
		/opt/Qt/5.14.2/ios/mkspecs/common/clang-mac.conf \
		/opt/Qt/5.14.2/ios/mkspecs/common/uikit/clang.conf \
		/opt/Qt/5.14.2/ios/mkspecs/common/uikit/qmake.conf \
		/opt/Qt/5.14.2/ios/mkspecs/qconfig.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_3danimation.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_3danimation_private.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_3dcore.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_3dcore_private.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_3dextras.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_3dextras_private.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_3dinput.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_3dinput_private.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_3dlogic.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_3dquick.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_3dquick_private.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_3dquickextras.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_3dquickinput.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_3dquickrender.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_3drender.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_3drender_private.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_bluetooth.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_core.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_core_private.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_edid_support_private.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_fb_support_private.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_gamepad.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_gamepad_private.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_graphics_support_private.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_gui.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_help.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_help_private.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_location.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_location_private.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_macextras.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_macextras_private.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_multimedia_private.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_network.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_network_private.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_nfc.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_nfc_private.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_opengl.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_opengl_private.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_openglextensions.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_positioning.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_positioning_private.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_positioningquick.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_qml.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_qmlmodels.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_qmltest_private.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_quick.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_quick_private.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_quickwidgets.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_remoteobjects.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_repparser.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_repparser_private.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_scxml.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_scxml_private.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_sensors.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_sensors_private.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_sql.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_svg.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_testlib.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_texttospeech.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_theme_support_private.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_uiplugin.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_uitools.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_uitools_private.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_webchannel.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_webchannel_private.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_websockets.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_websockets_private.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_webview.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_webview_private.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_widgets.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_xml.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_zlib_private.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_plugin_darwingamepad.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_plugin_defaultgeometryloader.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_plugin_gltfgeometryloader.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_plugin_gltfsceneexport.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_plugin_gltfsceneimport.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_plugin_qavfcamera.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_plugin_qavfmediaplayer.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_plugin_qgenericbearer.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_plugin_qgif.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_plugin_qicns.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_plugin_qico.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_plugin_qios.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_plugin_qiosnsphotolibrarysupport.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_plugin_qjpeg.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_plugin_qmacheif.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_plugin_qmacjp2.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_plugin_qminimal.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_plugin_qmldbg_debugger.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_plugin_qmldbg_inspector.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_plugin_qmldbg_local.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_plugin_qmldbg_messages.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_plugin_qmldbg_native.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_plugin_qmldbg_nativedebugger.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_plugin_qmldbg_preview.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_plugin_qmldbg_profiler.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_plugin_qmldbg_quickprofiler.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_plugin_qmldbg_server.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_plugin_qmldbg_tcp.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_plugin_qoffscreen.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_plugin_qsqlite.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_plugin_qsvg.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_plugin_qsvgicon.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_plugin_qtaudio_coreaudio.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_plugin_qtexttospeech_speechios.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_plugin_qtga.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_plugin_qtgeoservices_esri.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_plugin_qtgeoservices_itemsoverlay.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_plugin_qtgeoservices_mapbox.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_plugin_qtgeoservices_mapboxgl.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_plugin_qtgeoservices_nokia.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_plugin_qtgeoservices_osm.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_plugin_qtiff.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_plugin_qtmedia_audioengine.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_plugin_qtmultimedia_m3u.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_plugin_qtposition_cl.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_plugin_qtposition_positionpoll.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_plugin_qtsensorgestures_plugin.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_plugin_qtsensorgestures_shakeplugin.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_plugin_qtsensors_generic.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_plugin_qtsensors_ios.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_plugin_qtuiotouchplugin.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_plugin_qtwebview_darwin.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_plugin_qwbmp.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_plugin_qwebp.pri \
		/opt/Qt/5.14.2/ios/mkspecs/modules/qt_plugin_scene2d.pri \
		/opt/Qt/5.14.2/ios/mkspecs/features/qt_functions.prf \
		/opt/Qt/5.14.2/ios/mkspecs/features/qt_config.prf \
		/opt/Qt/5.14.2/ios/mkspecs/macx-ios-clang/qmake.conf \
		/opt/Qt/5.14.2/ios/mkspecs/macx-xcode/qmake.conf \
		/opt/Qt/5.14.2/ios/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/opt/Qt/5.14.2/ios/mkspecs/features/exclusive_builds.prf \
		/opt/Qt/5.14.2/ios/mkspecs/features/mac/sdk.prf \
		/opt/Qt/5.14.2/ios/mkspecs/features/uikit/sdk.prf \
		/opt/Qt/5.14.2/ios/mkspecs/features/toolchain.prf \
		/opt/Qt/5.14.2/ios/mkspecs/features/mac/toolchain.prf \
		/opt/Qt/5.14.2/ios/mkspecs/features/default_pre.prf \
		/opt/Qt/5.14.2/ios/mkspecs/features/mac/default_pre.prf \
		/opt/Qt/5.14.2/ios/mkspecs/features/uikit/default_pre.prf \
		../app/config.pri \
		../app/version.pri \
		../app/sources.pri \
		../app/android.pri \
		../app/ios.pri \
		../app/linux.pri \
		../app/macx.pri \
		../app/win32.pri \
		/opt/Qt/5.14.2/ios/mkspecs/features/resolve_config.prf \
		/opt/Qt/5.14.2/ios/mkspecs/features/uikit/resolve_config.prf \
		/opt/Qt/5.14.2/ios/mkspecs/features/default_post.prf \
		/opt/Qt/5.14.2/ios/mkspecs/features/mac/default_post.prf \
		/opt/Qt/5.14.2/ios/mkspecs/features/uikit/default_post.prf \
		/opt/Qt/5.14.2/ios/mkspecs/macx-ios-clang/features/default_post.prf \
		/opt/Qt/5.14.2/ios/mkspecs/features/mac/objective_c.prf \
		/opt/Qt/5.14.2/ios/mkspecs/features/resources_functions.prf \
		/opt/Qt/5.14.2/ios/mkspecs/features/qtquickcompiler.prf \
		/opt/Qt/5.14.2/ios/mkspecs/features/mac/mac.prf \
		/opt/Qt/5.14.2/ios/mkspecs/features/warn_on.prf \
		/opt/Qt/5.14.2/ios/plugins/platforms/libqios.prl \
		/opt/Qt/5.14.2/ios/mkspecs/features/qt.prf \
		/opt/Qt/5.14.2/ios/mkspecs/features/uikit/qt.prf \
		/opt/Qt/5.14.2/ios/mkspecs/features/gc_binaries.prf \
		/opt/Qt/5.14.2/ios/mkspecs/features/uikit/gc_binaries.prf \
		/opt/Qt/5.14.2/ios/mkspecs/features/resources.prf \
		/opt/Qt/5.14.2/ios/mkspecs/features/moc.prf \
		/opt/Qt/5.14.2/ios/mkspecs/features/unix/opengl.prf \
		/opt/Qt/5.14.2/ios/mkspecs/features/uic.prf \
		/opt/Qt/5.14.2/ios/mkspecs/features/unix/thread.prf \
		/opt/Qt/5.14.2/ios/mkspecs/features/qmake_use.prf \
		/opt/Qt/5.14.2/ios/mkspecs/features/file_copies.prf \
		/opt/Qt/5.14.2/ios/mkspecs/features/mac/rez.prf \
		/opt/Qt/5.14.2/ios/mkspecs/features/resolve_target.prf \
		/opt/Qt/5.14.2/ios/mkspecs/features/mac/asset_catalogs.prf \
		/opt/Qt/5.14.2/ios/mkspecs/features/testcase_targets.prf \
		/opt/Qt/5.14.2/ios/mkspecs/features/uikit/testcase_targets.prf \
		/opt/Qt/5.14.2/ios/mkspecs/features/exceptions.prf \
		/opt/Qt/5.14.2/ios/mkspecs/features/yacc.prf \
		/opt/Qt/5.14.2/ios/mkspecs/features/lex.prf \
		../app/input.pro \
		/opt/Qt/5.14.2/ios/mkspecs/macx-ios-clang/Default-568h@2x.png \
		/opt/Qt/5.14.2/ios/mkspecs/macx-ios-clang/LaunchScreen.xib \
		../app/img/pics.qrc \
		qml_qml_qmlcache.qrc \
		../app/fonts/fonts.qrc \
		../app/i18n/input_i18n.qrc \
		______opt_INPUT_input_sdk_ios_4_stage_arm64_QGIS.app_Contents_MacOS_qml_QgsQuick_qgsquick_qmlcache.qrc \
		/opt/INPUT/input-sdk-ios-4/stage/arm64/QGIS.app/Contents/Resources/images/QgsQuick/images.qrc \
		/opt/Qt/5.14.2/ios/lib/libQt5FontDatabaseSupport.prl \
		/opt/Qt/5.14.2/ios/lib/libqtfreetype.prl \
		/opt/Qt/5.14.2/ios/lib/libQt5GraphicsSupport.prl \
		/opt/Qt/5.14.2/ios/lib/libQt5ClipboardSupport.prl \
		/opt/Qt/5.14.2/ios/lib/libQt5Gui.prl \
		/opt/Qt/5.14.2/ios/lib/libqtlibpng.prl \
		/opt/Qt/5.14.2/ios/lib/libqtharfbuzz.prl \
		/opt/Qt/5.14.2/ios/lib/libQt5Core.prl \
		/opt/Qt/5.14.2/ios/lib/libqtpcre2.prl \
		/opt/Qt/5.14.2/ios/plugins/platforms/darwin/libqiosnsphotolibrarysupport.prl \
		/opt/Qt/5.14.2/ios/plugins/geoservices/libqtgeoservices_esri.prl \
		/opt/Qt/5.14.2/ios/plugins/geoservices/libqtgeoservices_itemsoverlay.prl \
		/opt/Qt/5.14.2/ios/plugins/geoservices/libqtgeoservices_mapbox.prl \
		/opt/Qt/5.14.2/ios/plugins/geoservices/libqtgeoservices_mapboxgl.prl \
		/opt/Qt/5.14.2/ios/plugins/geoservices/libqtgeoservices_nokia.prl \
		/opt/Qt/5.14.2/ios/plugins/geoservices/libqtgeoservices_osm.prl \
		/opt/Qt/5.14.2/ios/plugins/mediaservice/libqavfcamera.prl \
		/opt/Qt/5.14.2/ios/plugins/mediaservice/libqavfmediaplayer.prl \
		/opt/Qt/5.14.2/ios/plugins/mediaservice/libqtmedia_audioengine.prl \
		/opt/Qt/5.14.2/ios/plugins/audio/libqtaudio_coreaudio.prl \
		/opt/Qt/5.14.2/ios/plugins/playlistformats/libqtmultimedia_m3u.prl \
		/opt/Qt/5.14.2/ios/plugins/iconengines/libqsvgicon.prl \
		/opt/Qt/5.14.2/ios/plugins/imageformats/libqgif.prl \
		/opt/Qt/5.14.2/ios/plugins/imageformats/libqicns.prl \
		/opt/Qt/5.14.2/ios/plugins/imageformats/libqico.prl \
		/opt/Qt/5.14.2/ios/plugins/imageformats/libqjpeg.prl \
		/opt/Qt/5.14.2/ios/plugins/imageformats/libqmacheif.prl \
		/opt/Qt/5.14.2/ios/plugins/imageformats/libqmacjp2.prl \
		/opt/Qt/5.14.2/ios/plugins/imageformats/libqsvg.prl \
		/opt/Qt/5.14.2/ios/plugins/imageformats/libqtga.prl \
		/opt/Qt/5.14.2/ios/plugins/imageformats/libqtiff.prl \
		/opt/Qt/5.14.2/ios/plugins/imageformats/libqwbmp.prl \
		/opt/Qt/5.14.2/ios/plugins/imageformats/libqwebp.prl \
		/opt/Qt/5.14.2/ios/plugins/qmltooling/libqmldbg_debugger.prl \
		/opt/Qt/5.14.2/ios/plugins/qmltooling/libqmldbg_inspector.prl \
		/opt/Qt/5.14.2/ios/plugins/qmltooling/libqmldbg_local.prl \
		/opt/Qt/5.14.2/ios/plugins/qmltooling/libqmldbg_messages.prl \
		/opt/Qt/5.14.2/ios/plugins/qmltooling/libqmldbg_native.prl \
		/opt/Qt/5.14.2/ios/plugins/qmltooling/libqmldbg_nativedebugger.prl \
		/opt/Qt/5.14.2/ios/plugins/qmltooling/libqmldbg_preview.prl \
		/opt/Qt/5.14.2/ios/plugins/qmltooling/libqmldbg_profiler.prl \
		/opt/Qt/5.14.2/ios/plugins/qmltooling/libqmldbg_quickprofiler.prl \
		/opt/Qt/5.14.2/ios/plugins/qmltooling/libqmldbg_server.prl \
		/opt/Qt/5.14.2/ios/plugins/qmltooling/libqmldbg_tcp.prl \
		/opt/Qt/5.14.2/ios/plugins/bearer/libqgenericbearer.prl \
		/opt/Qt/5.14.2/ios/plugins/position/libqtposition_cl.prl \
		/opt/Qt/5.14.2/ios/plugins/position/libqtposition_positionpoll.prl \
		/opt/Qt/5.14.2/ios/plugins/sensors/libqtsensors_generic.prl \
		/opt/Qt/5.14.2/ios/plugins/sensors/libqtsensors_ios.prl \
		/opt/Qt/5.14.2/ios/plugins/sqldrivers/libqsqlite.prl \
		/opt/Qt/5.14.2/ios/lib/libQt5QuickControls2.prl \
		/opt/Qt/5.14.2/ios/lib/libQt5Location.prl \
		/opt/Qt/5.14.2/ios/lib/libQt5PositioningQuick.prl \
		/opt/Qt/5.14.2/ios/lib/libQt5Quick.prl \
		/opt/Qt/5.14.2/ios/lib/libQt5Svg.prl \
		/opt/Qt/5.14.2/ios/lib/libQt5OpenGL.prl \
		/opt/Qt/5.14.2/ios/lib/libQt5MultimediaWidgets.prl \
		/opt/Qt/5.14.2/ios/lib/libQt5Widgets.prl \
		/opt/Qt/5.14.2/ios/lib/libQt5Multimedia.prl \
		/opt/Qt/5.14.2/ios/lib/libQt5QmlModels.prl \
		/opt/Qt/5.14.2/ios/lib/libQt5Qml.prl \
		/opt/Qt/5.14.2/ios/lib/libQt5Network.prl \
		/opt/Qt/5.14.2/ios/lib/libQt5Xml.prl \
		/opt/Qt/5.14.2/ios/lib/libQt5Concurrent.prl \
		/opt/Qt/5.14.2/ios/lib/libQt5Positioning.prl \
		/opt/Qt/5.14.2/ios/lib/libQt5Sensors.prl \
		/opt/Qt/5.14.2/ios/lib/libQt5Sql.prl \
		/opt/Qt/5.14.2/ios/qml/QtQuick.2/libqtquick2plugin.prl \
		/opt/Qt/5.14.2/ios/qml/QtQuick/Controls.2/libqtquickcontrols2plugin.prl \
		/opt/Qt/5.14.2/ios/qml/QtQuick/Layouts/libqquicklayoutsplugin.prl \
		/opt/Qt/5.14.2/ios/qml/QtQuick/Dialogs/libdialogplugin.prl \
		/opt/Qt/5.14.2/ios/qml/QtGraphicalEffects/libqtgraphicaleffectsplugin.prl \
		/opt/Qt/5.14.2/ios/qml/QtQuick/Templates.2/libqtquicktemplates2plugin.prl \
		/opt/Qt/5.14.2/ios/qml/Qt/labs/folderlistmodel/libqmlfolderlistmodelplugin.prl \
		/opt/Qt/5.14.2/ios/qml/Qt/labs/settings/libqmlsettingsplugin.prl \
		/opt/Qt/5.14.2/ios/qml/QtQuick/Dialogs/Private/libdialogsprivateplugin.prl \
		/opt/Qt/5.14.2/ios/qml/QtQuick/Controls/libqtquickcontrolsplugin.prl \
		/opt/Qt/5.14.2/ios/qml/QtQuick/PrivateWidgets/libwidgetsplugin.prl \
		/opt/Qt/5.14.2/ios/qml/QtQml/libqmlplugin.prl \
		/opt/Qt/5.14.2/ios/qml/QtGraphicalEffects/private/libqtgraphicaleffectsprivate.prl \
		/opt/Qt/5.14.2/ios/qml/QtQuick/Window.2/libwindowplugin.prl \
		/opt/Qt/5.14.2/ios/qml/QtQuick/Shapes/libqmlshapesplugin.prl \
		/opt/Qt/5.14.2/ios/qml/QtMultimedia/libdeclarative_multimedia.prl \
		/opt/Qt/5.14.2/ios/qml/QtQml/Models.2/libmodelsplugin.prl \
		/opt/Qt/5.14.2/ios/qml/QtPositioning/libdeclarative_positioning.prl \
		/opt/Qt/5.14.2/ios/qml/QtQuick/Controls.2/Fusion/libqtquickcontrols2fusionstyleplugin.prl \
		/opt/Qt/5.14.2/ios/qml/QtQuick/Controls.2/Universal/libqtquickcontrols2universalstyleplugin.prl \
		/opt/Qt/5.14.2/ios/qml/QtQuick/Controls.2/Material/libqtquickcontrols2materialstyleplugin.prl \
		/opt/Qt/5.14.2/ios/qml/QtQuick/Controls.2/Imagine/libqtquickcontrols2imaginestyleplugin.prl
	$(QMAKE) -o Input.xcodeproj/project.pbxproj ../app/input.pro -spec macx-xcode CONFIG+=release CONFIG+=iphoneos CONFIG+=device CONFIG+=qtquickcompiler QMAKE_MAC_XCODE_SETTINGS+=qprofile qprofile.name=PROVISIONING_PROFILE_SPECIFIER qprofile.value=LutraConsultingLtd.Input.AppStore QMAKE_MAC_XCODE_SETTINGS+=qteam qteam.name=DEVELOPMENT_TEAM qteam.value=79QMH2QRAH QMAKE_MAC_XCODE_SETTINGS+=qidentity qidentity.name=CODE_SIGN_IDENTITY 'qidentity.value=iPhone Distribution: LUTRA CONSULTING LIMITED (79QMH2QRAH)' QMAKE_MAC_XCODE_SETTINGS+=qstyle qstyle.name=CODE_SIGN_STYLE qstyle.value=Manual
	@echo 'warning: Xcode project has been regenerated, custom settings have been lost. Use CONFIG+=no_autoqmake to prevent this behavior in the future, at the cost of requiring manual project change tracking.'
/opt/Qt/5.14.2/ios/mkspecs/features/spec_pre.prf:
/opt/Qt/5.14.2/ios/mkspecs/qdevice.pri:
/opt/Qt/5.14.2/ios/mkspecs/features/device_config.prf:
/opt/Qt/5.14.2/ios/mkspecs/common/unix.conf:
/opt/Qt/5.14.2/ios/mkspecs/common/mac.conf:
/opt/Qt/5.14.2/ios/mkspecs/common/uikit.conf:
/opt/Qt/5.14.2/ios/mkspecs/common/ios.conf:
/opt/Qt/5.14.2/ios/mkspecs/common/sanitize.conf:
/opt/Qt/5.14.2/ios/mkspecs/common/gcc-base.conf:
/opt/Qt/5.14.2/ios/mkspecs/common/gcc-base-mac.conf:
/opt/Qt/5.14.2/ios/mkspecs/common/clang.conf:
/opt/Qt/5.14.2/ios/mkspecs/common/clang-mac.conf:
/opt/Qt/5.14.2/ios/mkspecs/common/uikit/clang.conf:
/opt/Qt/5.14.2/ios/mkspecs/common/uikit/qmake.conf:
/opt/Qt/5.14.2/ios/mkspecs/qconfig.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_3danimation.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_3danimation_private.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_3dcore.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_3dcore_private.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_3dextras.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_3dextras_private.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_3dinput.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_3dinput_private.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_3dlogic.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_3dlogic_private.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_3dquick.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_3dquick_private.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_3dquickanimation.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_3dquickextras.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_3dquickinput.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_3dquickrender.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_3dquickscene2d.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_3drender.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_3drender_private.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_bluetooth.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_bluetooth_private.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_bootstrap_private.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_clipboard_support_private.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_concurrent.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_concurrent_private.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_core.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_core_private.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_edid_support_private.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_fb_support_private.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_gamepad.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_gamepad_private.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_graphics_support_private.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_gui.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_gui_private.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_help.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_help_private.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_location.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_location_private.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_macextras.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_macextras_private.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_multimedia.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_multimedia_private.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_multimediawidgets.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_network.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_network_private.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_nfc.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_nfc_private.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_opengl.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_opengl_private.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_openglextensions.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_openglextensions_private.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_positioning.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_positioning_private.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_positioningquick.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_positioningquick_private.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_qml.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_qml_private.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_qmldebug_private.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_qmlmodels.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_qmlmodels_private.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_qmltest.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_qmltest_private.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_qmlworkerscript.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_quick.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_quick_private.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_quickcontrols2.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_quickparticles_private.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_quickshapes_private.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_quicktemplates2.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_quickwidgets.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_remoteobjects.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_remoteobjects_private.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_repparser.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_repparser_private.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_scxml.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_scxml_private.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_sensors.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_sensors_private.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_sql.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_sql_private.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_svg.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_svg_private.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_testlib.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_testlib_private.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_texttospeech.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_texttospeech_private.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_theme_support_private.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_uiplugin.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_uitools.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_uitools_private.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_webchannel.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_webchannel_private.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_websockets.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_websockets_private.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_webview.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_webview_private.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_widgets.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_widgets_private.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_xml.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_xml_private.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_xmlpatterns.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_lib_zlib_private.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_plugin_darwingamepad.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_plugin_defaultgeometryloader.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_plugin_gltfgeometryloader.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_plugin_gltfsceneexport.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_plugin_gltfsceneimport.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_plugin_qavfcamera.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_plugin_qavfmediaplayer.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_plugin_qgenericbearer.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_plugin_qgif.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_plugin_qicns.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_plugin_qico.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_plugin_qios.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_plugin_qiosnsphotolibrarysupport.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_plugin_qjpeg.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_plugin_qmacheif.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_plugin_qmacjp2.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_plugin_qminimal.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_plugin_qmldbg_debugger.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_plugin_qmldbg_inspector.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_plugin_qmldbg_local.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_plugin_qmldbg_messages.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_plugin_qmldbg_native.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_plugin_qmldbg_nativedebugger.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_plugin_qmldbg_preview.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_plugin_qmldbg_profiler.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_plugin_qmldbg_quickprofiler.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_plugin_qmldbg_server.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_plugin_qmldbg_tcp.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_plugin_qoffscreen.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_plugin_qsqlite.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_plugin_qsvg.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_plugin_qsvgicon.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_plugin_qtaudio_coreaudio.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_plugin_qtexttospeech_speechios.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_plugin_qtga.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_plugin_qtgeoservices_esri.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_plugin_qtgeoservices_itemsoverlay.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_plugin_qtgeoservices_mapbox.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_plugin_qtgeoservices_mapboxgl.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_plugin_qtgeoservices_nokia.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_plugin_qtgeoservices_osm.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_plugin_qtiff.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_plugin_qtmedia_audioengine.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_plugin_qtmultimedia_m3u.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_plugin_qtposition_cl.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_plugin_qtposition_positionpoll.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_plugin_qtsensorgestures_plugin.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_plugin_qtsensorgestures_shakeplugin.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_plugin_qtsensors_generic.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_plugin_qtsensors_ios.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_plugin_qtuiotouchplugin.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_plugin_qtwebview_darwin.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_plugin_qwbmp.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_plugin_qwebp.pri:
/opt/Qt/5.14.2/ios/mkspecs/modules/qt_plugin_scene2d.pri:
/opt/Qt/5.14.2/ios/mkspecs/features/qt_functions.prf:
/opt/Qt/5.14.2/ios/mkspecs/features/qt_config.prf:
/opt/Qt/5.14.2/ios/mkspecs/macx-ios-clang/qmake.conf:
/opt/Qt/5.14.2/ios/mkspecs/macx-xcode/qmake.conf:
/opt/Qt/5.14.2/ios/mkspecs/features/spec_post.prf:
.qmake.stash:
/opt/Qt/5.14.2/ios/mkspecs/features/exclusive_builds.prf:
/opt/Qt/5.14.2/ios/mkspecs/features/mac/sdk.prf:
/opt/Qt/5.14.2/ios/mkspecs/features/uikit/sdk.prf:
/opt/Qt/5.14.2/ios/mkspecs/features/toolchain.prf:
/opt/Qt/5.14.2/ios/mkspecs/features/mac/toolchain.prf:
/opt/Qt/5.14.2/ios/mkspecs/features/default_pre.prf:
/opt/Qt/5.14.2/ios/mkspecs/features/mac/default_pre.prf:
/opt/Qt/5.14.2/ios/mkspecs/features/uikit/default_pre.prf:
../app/config.pri:
../app/version.pri:
../app/sources.pri:
../app/android.pri:
../app/ios.pri:
../app/linux.pri:
../app/macx.pri:
../app/win32.pri:
/opt/Qt/5.14.2/ios/mkspecs/features/resolve_config.prf:
/opt/Qt/5.14.2/ios/mkspecs/features/uikit/resolve_config.prf:
/opt/Qt/5.14.2/ios/mkspecs/features/default_post.prf:
/opt/Qt/5.14.2/ios/mkspecs/features/mac/default_post.prf:
/opt/Qt/5.14.2/ios/mkspecs/features/uikit/default_post.prf:
/opt/Qt/5.14.2/ios/mkspecs/macx-ios-clang/features/default_post.prf:
/opt/Qt/5.14.2/ios/mkspecs/features/mac/objective_c.prf:
/opt/Qt/5.14.2/ios/mkspecs/features/resources_functions.prf:
/opt/Qt/5.14.2/ios/mkspecs/features/qtquickcompiler.prf:
/opt/Qt/5.14.2/ios/mkspecs/features/mac/mac.prf:
/opt/Qt/5.14.2/ios/mkspecs/features/warn_on.prf:
/opt/Qt/5.14.2/ios/plugins/platforms/libqios.prl:
/opt/Qt/5.14.2/ios/mkspecs/features/qt.prf:
/opt/Qt/5.14.2/ios/mkspecs/features/uikit/qt.prf:
/opt/Qt/5.14.2/ios/mkspecs/features/gc_binaries.prf:
/opt/Qt/5.14.2/ios/mkspecs/features/uikit/gc_binaries.prf:
/opt/Qt/5.14.2/ios/mkspecs/features/resources.prf:
/opt/Qt/5.14.2/ios/mkspecs/features/moc.prf:
/opt/Qt/5.14.2/ios/mkspecs/features/unix/opengl.prf:
/opt/Qt/5.14.2/ios/mkspecs/features/uic.prf:
/opt/Qt/5.14.2/ios/mkspecs/features/unix/thread.prf:
/opt/Qt/5.14.2/ios/mkspecs/features/qmake_use.prf:
/opt/Qt/5.14.2/ios/mkspecs/features/file_copies.prf:
/opt/Qt/5.14.2/ios/mkspecs/features/mac/rez.prf:
/opt/Qt/5.14.2/ios/mkspecs/features/resolve_target.prf:
/opt/Qt/5.14.2/ios/mkspecs/features/mac/asset_catalogs.prf:
/opt/Qt/5.14.2/ios/mkspecs/features/testcase_targets.prf:
/opt/Qt/5.14.2/ios/mkspecs/features/uikit/testcase_targets.prf:
/opt/Qt/5.14.2/ios/mkspecs/features/exceptions.prf:
/opt/Qt/5.14.2/ios/mkspecs/features/yacc.prf:
/opt/Qt/5.14.2/ios/mkspecs/features/lex.prf:
../app/input.pro:
/opt/Qt/5.14.2/ios/mkspecs/macx-ios-clang/Default-568h@2x.png:
/opt/Qt/5.14.2/ios/mkspecs/macx-ios-clang/LaunchScreen.xib:
../app/img/pics.qrc:
qml_qml_qmlcache.qrc:
../app/fonts/fonts.qrc:
../app/i18n/input_i18n.qrc:
______opt_INPUT_input_sdk_ios_4_stage_arm64_QGIS.app_Contents_MacOS_qml_QgsQuick_qgsquick_qmlcache.qrc:
/opt/INPUT/input-sdk-ios-4/stage/arm64/QGIS.app/Contents/Resources/images/QgsQuick/images.qrc:
/opt/Qt/5.14.2/ios/lib/libQt5FontDatabaseSupport.prl:
/opt/Qt/5.14.2/ios/lib/libqtfreetype.prl:
/opt/Qt/5.14.2/ios/lib/libQt5GraphicsSupport.prl:
/opt/Qt/5.14.2/ios/lib/libQt5ClipboardSupport.prl:
/opt/Qt/5.14.2/ios/lib/libQt5Gui.prl:
/opt/Qt/5.14.2/ios/lib/libqtlibpng.prl:
/opt/Qt/5.14.2/ios/lib/libqtharfbuzz.prl:
/opt/Qt/5.14.2/ios/lib/libQt5Core.prl:
/opt/Qt/5.14.2/ios/lib/libqtpcre2.prl:
/opt/Qt/5.14.2/ios/plugins/platforms/darwin/libqiosnsphotolibrarysupport.prl:
/opt/Qt/5.14.2/ios/plugins/geoservices/libqtgeoservices_esri.prl:
/opt/Qt/5.14.2/ios/plugins/geoservices/libqtgeoservices_itemsoverlay.prl:
/opt/Qt/5.14.2/ios/plugins/geoservices/libqtgeoservices_mapbox.prl:
/opt/Qt/5.14.2/ios/plugins/geoservices/libqtgeoservices_mapboxgl.prl:
/opt/Qt/5.14.2/ios/plugins/geoservices/libqtgeoservices_nokia.prl:
/opt/Qt/5.14.2/ios/plugins/geoservices/libqtgeoservices_osm.prl:
/opt/Qt/5.14.2/ios/plugins/mediaservice/libqavfcamera.prl:
/opt/Qt/5.14.2/ios/plugins/mediaservice/libqavfmediaplayer.prl:
/opt/Qt/5.14.2/ios/plugins/mediaservice/libqtmedia_audioengine.prl:
/opt/Qt/5.14.2/ios/plugins/audio/libqtaudio_coreaudio.prl:
/opt/Qt/5.14.2/ios/plugins/playlistformats/libqtmultimedia_m3u.prl:
/opt/Qt/5.14.2/ios/plugins/iconengines/libqsvgicon.prl:
/opt/Qt/5.14.2/ios/plugins/imageformats/libqgif.prl:
/opt/Qt/5.14.2/ios/plugins/imageformats/libqicns.prl:
/opt/Qt/5.14.2/ios/plugins/imageformats/libqico.prl:
/opt/Qt/5.14.2/ios/plugins/imageformats/libqjpeg.prl:
/opt/Qt/5.14.2/ios/plugins/imageformats/libqmacheif.prl:
/opt/Qt/5.14.2/ios/plugins/imageformats/libqmacjp2.prl:
/opt/Qt/5.14.2/ios/plugins/imageformats/libqsvg.prl:
/opt/Qt/5.14.2/ios/plugins/imageformats/libqtga.prl:
/opt/Qt/5.14.2/ios/plugins/imageformats/libqtiff.prl:
/opt/Qt/5.14.2/ios/plugins/imageformats/libqwbmp.prl:
/opt/Qt/5.14.2/ios/plugins/imageformats/libqwebp.prl:
/opt/Qt/5.14.2/ios/plugins/qmltooling/libqmldbg_debugger.prl:
/opt/Qt/5.14.2/ios/plugins/qmltooling/libqmldbg_inspector.prl:
/opt/Qt/5.14.2/ios/plugins/qmltooling/libqmldbg_local.prl:
/opt/Qt/5.14.2/ios/plugins/qmltooling/libqmldbg_messages.prl:
/opt/Qt/5.14.2/ios/plugins/qmltooling/libqmldbg_native.prl:
/opt/Qt/5.14.2/ios/plugins/qmltooling/libqmldbg_nativedebugger.prl:
/opt/Qt/5.14.2/ios/plugins/qmltooling/libqmldbg_preview.prl:
/opt/Qt/5.14.2/ios/plugins/qmltooling/libqmldbg_profiler.prl:
/opt/Qt/5.14.2/ios/plugins/qmltooling/libqmldbg_quickprofiler.prl:
/opt/Qt/5.14.2/ios/plugins/qmltooling/libqmldbg_server.prl:
/opt/Qt/5.14.2/ios/plugins/qmltooling/libqmldbg_tcp.prl:
/opt/Qt/5.14.2/ios/plugins/bearer/libqgenericbearer.prl:
/opt/Qt/5.14.2/ios/plugins/position/libqtposition_cl.prl:
/opt/Qt/5.14.2/ios/plugins/position/libqtposition_positionpoll.prl:
/opt/Qt/5.14.2/ios/plugins/sensors/libqtsensors_generic.prl:
/opt/Qt/5.14.2/ios/plugins/sensors/libqtsensors_ios.prl:
/opt/Qt/5.14.2/ios/plugins/sqldrivers/libqsqlite.prl:
/opt/Qt/5.14.2/ios/lib/libQt5QuickControls2.prl:
/opt/Qt/5.14.2/ios/lib/libQt5Location.prl:
/opt/Qt/5.14.2/ios/lib/libQt5PositioningQuick.prl:
/opt/Qt/5.14.2/ios/lib/libQt5Quick.prl:
/opt/Qt/5.14.2/ios/lib/libQt5Svg.prl:
/opt/Qt/5.14.2/ios/lib/libQt5OpenGL.prl:
/opt/Qt/5.14.2/ios/lib/libQt5MultimediaWidgets.prl:
/opt/Qt/5.14.2/ios/lib/libQt5Widgets.prl:
/opt/Qt/5.14.2/ios/lib/libQt5Multimedia.prl:
/opt/Qt/5.14.2/ios/lib/libQt5QmlModels.prl:
/opt/Qt/5.14.2/ios/lib/libQt5Qml.prl:
/opt/Qt/5.14.2/ios/lib/libQt5Network.prl:
/opt/Qt/5.14.2/ios/lib/libQt5Xml.prl:
/opt/Qt/5.14.2/ios/lib/libQt5Concurrent.prl:
/opt/Qt/5.14.2/ios/lib/libQt5Positioning.prl:
/opt/Qt/5.14.2/ios/lib/libQt5Sensors.prl:
/opt/Qt/5.14.2/ios/lib/libQt5Sql.prl:
/opt/Qt/5.14.2/ios/qml/QtQuick.2/libqtquick2plugin.prl:
/opt/Qt/5.14.2/ios/qml/QtQuick/Controls.2/libqtquickcontrols2plugin.prl:
/opt/Qt/5.14.2/ios/qml/QtQuick/Layouts/libqquicklayoutsplugin.prl:
/opt/Qt/5.14.2/ios/qml/QtQuick/Dialogs/libdialogplugin.prl:
/opt/Qt/5.14.2/ios/qml/QtGraphicalEffects/libqtgraphicaleffectsplugin.prl:
/opt/Qt/5.14.2/ios/qml/QtQuick/Templates.2/libqtquicktemplates2plugin.prl:
/opt/Qt/5.14.2/ios/qml/Qt/labs/folderlistmodel/libqmlfolderlistmodelplugin.prl:
/opt/Qt/5.14.2/ios/qml/Qt/labs/settings/libqmlsettingsplugin.prl:
/opt/Qt/5.14.2/ios/qml/QtQuick/Dialogs/Private/libdialogsprivateplugin.prl:
/opt/Qt/5.14.2/ios/qml/QtQuick/Controls/libqtquickcontrolsplugin.prl:
/opt/Qt/5.14.2/ios/qml/QtQuick/PrivateWidgets/libwidgetsplugin.prl:
/opt/Qt/5.14.2/ios/qml/QtQml/libqmlplugin.prl:
/opt/Qt/5.14.2/ios/qml/QtGraphicalEffects/private/libqtgraphicaleffectsprivate.prl:
/opt/Qt/5.14.2/ios/qml/QtQuick/Window.2/libwindowplugin.prl:
/opt/Qt/5.14.2/ios/qml/QtQuick/Shapes/libqmlshapesplugin.prl:
/opt/Qt/5.14.2/ios/qml/QtMultimedia/libdeclarative_multimedia.prl:
/opt/Qt/5.14.2/ios/qml/QtQml/Models.2/libmodelsplugin.prl:
/opt/Qt/5.14.2/ios/qml/QtPositioning/libdeclarative_positioning.prl:
/opt/Qt/5.14.2/ios/qml/QtQuick/Controls.2/Fusion/libqtquickcontrols2fusionstyleplugin.prl:
/opt/Qt/5.14.2/ios/qml/QtQuick/Controls.2/Universal/libqtquickcontrols2universalstyleplugin.prl:
/opt/Qt/5.14.2/ios/qml/QtQuick/Controls.2/Material/libqtquickcontrols2materialstyleplugin.prl:
/opt/Qt/5.14.2/ios/qml/QtQuick/Controls.2/Imagine/libqtquickcontrols2imaginestyleplugin.prl:
qmake: FORCE
	@$(QMAKE) -o Input.xcodeproj/project.pbxproj ../app/input.pro -spec macx-xcode CONFIG+=release CONFIG+=iphoneos CONFIG+=device CONFIG+=qtquickcompiler QMAKE_MAC_XCODE_SETTINGS+=qprofile qprofile.name=PROVISIONING_PROFILE_SPECIFIER qprofile.value=LutraConsultingLtd.Input.AppStore QMAKE_MAC_XCODE_SETTINGS+=qteam qteam.name=DEVELOPMENT_TEAM qteam.value=79QMH2QRAH QMAKE_MAC_XCODE_SETTINGS+=qidentity qidentity.name=CODE_SIGN_IDENTITY 'qidentity.value=iPhone Distribution: LUTRA CONSULTING LIMITED (79QMH2QRAH)' QMAKE_MAC_XCODE_SETTINGS+=qstyle qstyle.name=CODE_SIGN_STYLE qstyle.value=Manual

qmake_all: FORCE

