# GPLv2 Licence

set(absl_libs
    decode_rust_punycode
    demangle_rust
    flags_commandlineflag
    flags_commandlineflag_internal
    flags_config;flags_internal
    flags_marshalling;flags_parse
    flags_private_handle_accessor;flags_program_name
    flags_reflection;flags_usage
    flags_usage_internal
    log_flags;log_internal_structured_proto
    poison
    tracing_internal
    utf8_for_code_point
    atomic_hook
    errno_saver
    log_severity
    no_destructor
    nullability
    raw_logging_internal
    spinlock_wait
    config
    dynamic_annotations
    core_headers
    malloc_internal
    base_internal
    base
    throw_delegate
    pretty_function
    endian
    scoped_set_env
    strerror
    fast_type_id
    prefetch
    poison
    tracing_internal
    algorithm
    algorithm_container
    cleanup_internal
    cleanup
    btree
    compressed_tuple
    fixed_array
    inlined_vector_internal
    inlined_vector
    flat_hash_map
    flat_hash_set
    node_hash_map
    node_hash_set
    hash_container_defaults
    container_memory
    hash_function_defaults
    hash_policy_traits
    common_policy_traits
    hashtablez_sampler
    hashtable_debug
    hashtable_debug_hooks
    node_slot_policy
    raw_hash_map
    container_common
    raw_hash_set
    layout
    crc_cpu_detect
    crc_internal
    crc32c
    non_temporal_arm_intrinsics
    non_temporal_memcpy
    crc_cord_state
    stacktrace
    symbolize
    examine_stack
    failure_signal_handler
    debugging_internal
    demangle_internal
    bounded_utf8_length_sequence
    decode_rust_punycode
    demangle_rust
    utf8_for_code_point
    leak_check
    debugging
    flags_path_util
    flags_program_name
    flags_config
    flags_marshalling
    flags_commandlineflag_internal
    flags_commandlineflag
    flags_private_handle_accessor
    flags_reflection
    flags_internal
    flags
    flags_usage_internal
    flags_usage
    flags_parse
    any_invocable
    bind_front
    function_ref
    overload
    hash
    city
    low_level_hash
    log_internal_check_impl
    log_internal_check_op
    log_internal_conditions
    log_internal_config
    log_internal_flags
    log_internal_format
    log_internal_globals
    log_internal_log_impl
    log_internal_proto
    log_internal_message
    log_internal_log_sink_set
    log_internal_nullguard
    log_internal_nullstream
    log_internal_strip
    log_internal_voidify
    log_internal_append_truncated
    check
    log
    check
    die_if_null
    log_flags
    log_globals
    log_initialize
    log
    log_entry
    log_sink
    log_sink_registry
    log_streamer
    log_internal_structured
    log_internal_structured_proto
    log_structured
    vlog_config_internal
    vlog_is_on
    vlog_is_on
    log_internal_fnmatch
    memory
    type_traits
    meta
    bits
    int128
    numeric
    numeric_representation
    sample_recorder
    exponential_biased
    periodic_sampler
    random_random
    random_bit_gen_ref
    random_internal_mock_helpers
    random_distributions
    random_seed_gen_exception
    random_seed_sequences
    random_internal_traits
    random_internal_distribution_caller
    random_internal_fast_uniform_bits
    random_internal_seed_material
    random_internal_pool_urbg
    random_internal_salted_seed_seq
    random_internal_iostream_state_saver
    random_internal_generate_real
    random_internal_wide_multiply
    random_internal_fastmath
    random_internal_nonsecure_base
    random_internal_pcg_engine
    random_internal_randen_engine
    random_internal_platform
    random_internal_randen
    random_internal_randen_slow
    random_internal_randen_hwaes
    random_internal_randen_hwaes_impl
    random_internal_distribution_test_util
    random_internal_uniform_helper
    status
    statusor
    string_view
    strings
    charset
    has_ostream_operator
    strings_internal
    str_format
    str_format_internal
    cord_internal
    cordz_update_tracker
    cordz_functions
    cordz_statistics
    cordz_handle
    cordz_info
    cordz_sample_token
    cordz_update_scope
    cord
    graphcycles_internal
    kernel_timeout_internal
    synchronization
    time
    civil_time
    time_zone
    any
    bad_any_cast
    bad_any_cast_impl
    span
    optional
    bad_optional_access
    bad_variant_access
    variant
    compare
    utility
    if_constexpr
)

foreach (absl_lib IN ITEMS ${absl_libs})

  find_library(
    absl_${absl_lib}_LIBRARY
    NAMES absl_${absl_lib} libabsl_${absl_lib}
    PATHS "${INPUT_SDK_PATH_MULTI}/lib"
    NO_DEFAULT_PATH
  )

  if (EXISTS ${absl_${absl_lib}_LIBRARY})
    if (NOT TARGET Absl::absl_${absl_lib})
      add_library(Absl::absl_${absl_lib} UNKNOWN IMPORTED)
      set_target_properties(
        Absl::absl_${absl_lib} PROPERTIES IMPORTED_LOCATION "${absl_${absl_lib}_LIBRARY}"
      )

      set(ABSL_TARGETS "${ABSL_TARGETS};Absl::absl_${absl_lib}")
    endif ()
  endif ()

endforeach ()

find_package_handle_standard_args(Absl REQUIRED_VARS ABSL_TARGETS)
